# Thesis: Reclaimed Timber in Deep Generative Design
**Notebook ID:** c22_timber_stock_dataset_generation  
**Author:** Jasper Cluistra   
**Last Updated:** 2026-04-21
### Timber stock dataset generation script
**Goal:** Generate the timber stock datasets that the algorithm can use to choose elements for the design.

**Inputs:**
*   Parameters for stock properties

**Outputs:**
*   CSV file with datasets for new stock and reclaimed stock

# STOCK GENERATION

In [1]:
import pandas as pd
import config
from c16_generation_timber import generate_new_stock, generate_reclaimed_stock

efficient = True  # Set to True for efficient transport distances, False for realistic distances

# GENERATE NEW STOCK
df_new_stock = generate_new_stock(efficient)
display(df_new_stock.head(3))

# GENERATE RECLAIMED STOCK
df_reclaimed_stock = generate_reclaimed_stock()
display(df_reclaimed_stock.head(3))

# Combine both datasets into one large matrix
df_combined_stock = pd.concat([df_new_stock, df_reclaimed_stock], ignore_index=True)

# Export
new_stock_dataset_filename = 'new_timber_v2.csv'
df_new_stock.to_csv(config.TIMBER_STOCK_PATH / new_stock_dataset_filename, index=False, sep=';')
combined_dataset_filename = 'complete_timber_v2.csv'
df_combined_stock.to_csv(config.TIMBER_STOCK_PATH / combined_dataset_filename, index=False, sep=';')

print(f"New stock dataset saved as '{new_stock_dataset_filename}'.")
print(f"Combined dataset saved as '{combined_dataset_filename}'.")

Config System loaded successfully, Code running locally from thesis_generative_timber and Data is connected to OneDrive 2.2 - 2.4.

Loaded summary statistics: average_length_mm=2978.3, min_length_mm=1101.4, max_length_mm=5102.2, total_length_mm=357399.7, edge_count=120
Generating catalog... primary=306 beam types, tail=48 beam types
Length source stats (new stock): primary from pooled p5-p95 -> primary_lengths=(1800, 2100, 2400, 2700, 3000, 3300, 3600, 3900, 4200); short tail from structural min-x to primary-start-x -> (800, 900, 1200, 1500); long tail from primary-end+x to structural max+x -> (4500, 4800, 5100, 5400)
Generated length sets (mm): primary=(1800, 2100, 2400, 2700, 3000, 3300, 3600, 3900, 4200), short_tail=(800, 900, 1200, 1500), long_tail=(4500, 4800, 5100, 5400), tail_margin_mm=300, tail_section_count=6
New stock generated successfully! (354 elements)

,Member_ID,State,Length,Depth,Width,Length_Category,Availability_Probability,f_mk,f_tk,E_modulus_eff,E_modulus_005,f_vk,f_c0k,k_density,mean_density,Origin_Country,Transport_Dist,EmissionFactor
0,NS_00000,0,1800.0,100.0,38.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Netherlands,56.80,0.1726
1,NS_00001,0,1800.0,100.0,50.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Germany,258.19,0.1712
2,NS_00002,0,1800.0,100.0,63.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Netherlands,52.86,0.1770

Length source stats (reclaimed stock): mean from pooled p50=2995.9 mm, spread from p5-p95=1698.6-4275.7 mm hard bounds from pooled p1-p99=1230.4-4891.2 mm
Reclaimed length range (mm): 1250 to 4900
Reclaimed stock generated successfully! (70 elements)

,Member_ID,State,Length,Depth,Width,Length_Category,Availability_Probability,f_mk,f_tk,E_modulus_eff,E_modulus_005,f_vk,f_c0k,k_density,mean_density,Origin_Country,Transport_Dist,EmissionFactor
0,RS_00001,1,3650.0,150.0,50.0,primary,0.3,18.0,11.0,9000.0,6000.0,2.0,18.0,320.0,380.0,Netherlands,99,0.0409
1,RS_00002,1,1750.0,170.0,60.0,primary,0.3,18.0,11.0,9000.0,6000.0,2.0,18.0,320.0,380.0,Netherlands,83,0.0429
2,RS_00003,1,2800.0,230.0,70.0,primary,1.0,18.0,11.0,9000.0,6000.0,2.0,18.0,320.0,380.0,Netherlands,194,0.1723

New stock dataset saved as 'new_timber_v2.csv'.
Combined dataset saved as 'complete_timber_v2.csv'.

## CHECK COMBINATIONS

In [2]:
'''
# TABLE WITH DEPTH AND WIDTH
print("\n" + "="*50)
print("TABLE: ALL DEPTH AND WIDTH COMBINATIONS")
print("="*50)

depth_width_combinations = df_new_stock[['Depth', 'Width']].drop_duplicates().sort_values(by=['Depth', 'Width']).reset_index(drop=True)

print(f"\n{'Basic size':<15} {'D (mm)':<12} {'W (mm)':<12}")
print("-" * 40)

for idx, (_, row) in enumerate(depth_width_combinations.iterrows(), 1):
    depth = int(row['Depth'])
    width = int(row['Width'])
    print(f"{idx:<15} {depth:<12} {width:<12}")

print("-" * 40)
print(f"Total number of combinations: {len(depth_width_combinations)}")

# depth_width_combinations.to_csv('depth_width_combinations.csv', index=False)
# print("\nExported to 'depth_width_combinations.csv'")
'''

'\n# TABLE WITH DEPTH AND WIDTH\nprint("\n" + "="*50)\nprint("TABLE: ALL DEPTH AND WIDTH COMBINATIONS")\nprint("="*50)\n\ndepth_width_combinations = df_new_stock[[\'Depth\', \'Width\']].drop_duplicates().sort_values(by=[\'Depth\', \'Width\']).reset_index(drop=True)\n\nprint(f"\n{\'Basic size\':<15} {\'D (mm)\':<12} {\'W (mm)\':<12}")\nprint("-" * 40)\n\nfor idx, (_, row) in enumerate(depth_width_combinations.iterrows(), 1):\n    depth = int(row[\'Depth\'])\n    width = int(row[\'Width\'])\n    print(f"{idx:<15} {depth:<12} {width:<12}")\n\nprint("-" * 40)\nprint(f"Total number of combinations: {len(depth_width_combinations)}")\n\n# depth_width_combinations.to_csv(\'depth_width_combinations.csv\', index=False)\n# print("\nExported to \'depth_width_combinations.csv\'")\n'

## SUBSET

In [3]:
import config
from c16_generation_timber import generate_mixed_stock_subset

# Generate a smaller subset for testing purposes
df_small = generate_mixed_stock_subset(
    total_elements=20,
    reclaimed_ratio=0.3,
    random_state=38,
    allow_replacement=True
)

display(df_small.head(5))
dataset_filename = 'complete_timber_small.csv'
df_small.to_csv(config.TIMBER_STOCK_PATH / dataset_filename, index=False)

Generating catalog... primary=306 beam types, tail=48 beam types
Length source stats (new stock): primary from pooled p5-p95 -> primary_lengths=(1800, 2100, 2400, 2700, 3000, 3300, 3600, 3900, 4200); short tail from structural min-x to primary-start-x -> (800, 900, 1200, 1500); long tail from primary-end+x to structural max+x -> (4500, 4800, 5100, 5400)
Generated length sets (mm): primary=(1800, 2100, 2400, 2700, 3000, 3300, 3600, 3900, 4200), short_tail=(800, 900, 1200, 1500), long_tail=(4500, 4800, 5100, 5400), tail_margin_mm=300, tail_section_count=6
New stock generated successfully! (354 elements)
Length source stats (reclaimed stock): mean from pooled p50=2995.9 mm, spread from p5-p95=1698.6-4275.7 mm hard bounds from pooled p1-p99=1230.4-4891.2 mm
Reclaimed length range (mm): 1250 to 4550
Reclaimed stock generated successfully! (70 elements)
Mixed subset generated: 20 total | new=14, reclaimed=6 (reclaimed_ratio=0.30)

,Member_ID,State,Length,Depth,Width,Length_Category,Availability_Probability,f_mk,f_tk,E_modulus_eff,E_modulus_005,f_vk,f_c0k,k_density,mean_density,Origin_Country,Transport_Dist,EmissionFactor
0,NS_00074,0,2400.0,150.0,50.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Finland,2052.41,0.1760
1,NS_00081,0,2400.0,175.0,75.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Netherlands,54.59,0.1765
2,NS_00305,0,4200.0,300.0,300.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Other,3770.62,0.1763
3,NS_00148,0,3000.0,175.0,63.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Poland,777.67,0.1709
4,NS_00011,0,1800.0,175.0,50.0,primary,1.0,24.0,14.0,11000.0,7400.0,2.5,21.0,350.0,420.0,Netherlands,49.66,0.1705